### ISSUE TITLE
The SQL rewriter does not split the privacy budget across aggregations

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/whitenoise-system#200]
The privacy guarantees of the SQL PrivateReader should hold for a query in its totality, but this is currently not the case: when many aggregations are present in the same query, the privacy budget is not split between them.

This allows averaging attacks like [demonstrated here](https://twitter.com/TedOnPrivacy/status/1263554173007691776); though of course this also would affect a well-meaning user who simply want to do multiple aggregations.

Worse, this also affects a user who simply does *one* aggregation like SUM: if I understand [this code](https://github.com/opendifferentialprivacy/whitenoise-system/blob/60743c0a6bd2002296764a5c388e999c2b99a7dd/sdk/opendp/whitenoise/sql/private_reader.py#L117) correctly, this will transparently add a "count users" aggregation to do the threshold check and remove dimensions with too few users in them. This aggregation will also use the full privacy budget, so the total privacy budget of the query will be underestimated by a factor of 2.

**Comment by joshua-oss** [comment]
Thanks for flagging.  The get_privacy_cost method on PrivateReader is intended to get the total privacy cost of a query (a multiple of epsilon), since the reader is created once and used repeatedly, with different queries typically using different amounts of budget.  The API calling pattern doesn't expose this clearly, so we need to revisit and revise this.

**Comment by joshua-oss** [comment]
PR #208 updates the parameter name to make the behavior more clear.
